#define glCullFace		
#define glFrontFace	
#define glHint		
#define glLineWidth	
#define glPointSize	
#define glPolygonMode	
#define glScissor		
#define glTexParameterf	
#define glTexParameterfv	
#define glTexParameteri	
#define glTexParameteriv	
#define glTexImage1D	
#define glTexImage2D	
#define glDrawBuffer	
#define glClear		
#define glClearColor	
#define glClearStencil	
#define glClearDepth	
#define glStencilMask	
#define glColorMask	
#define glDepthMask	
#define glDisable		
#define glEnable		
#define glFinish		
#define glFlush		
#define glBlendFunc	
#define glLogicOp		
#define glStencilFunc	
#define glStencilOp	
#define glDepthFunc	
#define glPixelStoref	
#define glPixelStorei	
#define glReadBuffer	
#define glReadPixels	
#define glGetBooleanv	
#define glGetDoublev	
#define glGetError		
#define glGetFloatv	
#define glGetIntegerv	
#define glGetString	
#define glGetTexImage	
#define glGetTexParameterfv	
#define glGetTexParameteriv	
#define glGetTexLevelParameterfv
#define glGetTexLevelParameteriv
#define glIsEnabled		
#define glDepthRange		
#define glViewport		
#define glDrawArrays		
#define glDrawElements		
#define glPolygonOffset		
#define glCopyTexImage1D		
#define glCopyTexImage2D		
#define glCopyTexSubImage1D	
#define glCopyTexSubImage2D	
#define glTexSubImage1D		
#define glTexSubImage2D		
#define glBindTexture		
#define glDeleteTextures		
#define glGenTextures		
#define glIsTexture		
#define glDrawRangeElements	
#define glTexImage3D
#define glTexSubImage3D		
#define glCopyTexSubImage3D	
#define glActiveTexture		
#define glSampleCoverage		
#define glCompressedTexImage3D	
#define glCompressedTexImage2D	
#define glCompressedTexImage1D	
#define glCompressedTexSubImage3D	
#define glCompressedTexSubImage2D	
#define glCompressedTexSubImage1D	
#define glGetCompressedTexImage	
#define glBlendFuncSeparate	
#define glMultiDrawArrays		
#define glMultiDrawElements	
#define glPointParameterf		
#define glPointParameterfv		
#define glPointParameteri		
#define glPointParameteriv		
#define glBlendColor		
#define glBlendEquation		
#define glGenQueries		
#define glDeleteQueries		
#define glIsQuery		
#define glBeginQuery		
#define glEndQuery		
#define glGetQueryiv		
#define glGetQueryObjectiv		
#define glGetQueryObjectuiv	
#define glBindBuffer		
#define glDeleteBuffers		
#define glGenBuffers		
#define glIsBuffer		
#define glBufferData		
#define glBufferSubData		
#define glGetBufferSubData		
#define glMapBuffer		
#define glUnmapBuffer		
#define glGetBufferParameteriv	
#define glGetBufferPointerv	
#define glBlendEquationSeparate	
#define glDrawBuffers		
#define glStencilOpSeparate	
#define glStencilFuncSeparate	
#define glStencilMaskSeparate	
#define glAttachShader		
#define glBindAttribLocation	
#define glCompileShader		
#define glCreateProgram		
#define glCreateShader		
#define glDeleteProgram		
#define glDeleteShader		
#define glDetachShader		
#define glDisableVertexAttribArray	
#define glEnableVertexAttribArray	
#define glGetActiveAttrib		
#define glGetActiveUniform		
#define glGetAttachedShaders	
#define glGetAttribLocation	
#define glGetProgramiv		
#define glGetProgramInfoLog	
#define glGetShaderiv		
#define glGetShaderInfoLog		
#define glGetShaderSource		
#define glGetUniformLocation	
#define glGetUniformfv		
#define glGetUniformiv		
#define glGetVertexAttribdv	
#define glGetVertexAttribfv	
#define glGetVertexAttribiv	
#define glGetVertexAttribPointerv	
#define glIsProgram		
#define glIsShader		
#define glLinkProgram		
#define glShaderSource		
#define glUseProgram		
#define glUniform1f		
#define glUniform2f		
#define glUniform3f		
#define glUniform4f		
#define glUniform1i		
#define glUniform2i		
#define glUniform3i		
#define glUniform4i		
#define glUniform1fv		
#define glUniform2fv		
#define glUniform3fv		
#define glUniform4fv		
#define glUniform1iv		
#define glUniform2iv		
#define glUniform3iv		
#define glUniform4iv		
#define glUniformMatrix2fv		
#define glUniformMatrix3fv		
#define glUniformMatrix4fv		
#define glValidateProgram		
#define glVertexAttrib1d		
#define glVertexAttrib1dv		
#define glVertexAttrib1f		
#define glVertexAttrib1fv		
#define glVertexAttrib1s		
#define glVertexAttrib1sv		
#define glVertexAttrib2d		
#define glVertexAttrib2dv		
#define glVertexAttrib2f		
#define glVertexAttrib2fv		
#define glVertexAttrib2s		
#define glVertexAttrib2sv		
#define glVertexAttrib3d		
#define glVertexAttrib3dv		
#define glVertexAttrib3f		
#define glVertexAttrib3fv		
#define glVertexAttrib3s		
#define glVertexAttrib3sv		
#define glVertexAttrib4Nbv		
#define glVertexAttrib4Niv		
#define glVertexAttrib4Nsv		
#define glVertexAttrib4Nub		
#define glVertexAttrib4Nubv	
#define glVertexAttrib4Nuiv	
#define glVertexAttrib4Nusv	
#define glVertexAttrib4bv		
#define glVertexAttrib4d		
#define glVertexAttrib4dv		
#define glVertexAttrib4f		
#define glVertexAttrib4fv		
#define glVertexAttrib4iv		
#define glVertexAttrib4s		
#define glVertexAttrib4sv		
#define glVertexAttrib4ubv		
#define glVertexAttrib4uiv		
#define glVertexAttrib4usv		
#define glVertexAttribPointer	
#define glUniformMatrix2x3f	
#define glUniformMatrix3x2fv	
#define glUniformMatrix2x4fv	
#define glUniformMatrix4x2fv	
#define glUniformMatrix3x4fv	
#define glUniformMatrix4x3fv	
#define glColorMaski		
#define glGetBooleani_v		
#define glGetIntegeri_v		
#define glEnablei		 
#define glDisablei		 
#define glIsEnabledi		
#define glBeginTransformFeedback	
#define glEndTransformFeedback	
#define glBindBufferRange		
#define glBindBufferBase		
#define glTransformFeedbackVaryings
#define glGetTransformFeedbackVarying
#define glClampColor		
#define glBeginConditionalRender
#define glEndConditionalRender	
#define glVertexAttribIPointer	
#define glGetVertexAttribIiv	
#define glGetVertexAttribIuiv	
#define glVertexAttribI1i		
#define glVertexAttribI2i		
#define glVertexAttribI3i		
#define glVertexAttribI4i		
#define glVertexAttribI1ui		
#define glVertexAttribI2ui		
#define glVertexAttribI3ui		
#define glVertexAttribI4ui		
#define glVertexAttribI1iv		
#define glVertexAttribI2iv		
#define glVertexAttribI3iv		
#define glVertexAttribI4iv		
#define glVertexAttribI1uiv	
#define glVertexAttribI2uiv	
#define glVertexAttribI3uiv	
#define glVertexAttribI4uiv	
#define glVertexAttribI4bv		
#define glVertexAttribI4sv		
#define glVertexAttribI4ubv	
#define glVertexAttribI4usv	
#define glGetUniformuiv		
#define glBindFragDataLocation	
#define glGetFragDataLocation	
#define glUniform1ui		
#define glUniform2ui		
#define glUniform3ui		
#define glUniform4ui		
#define glUniform1uiv		
#define glUniform2uiv		
#define glUniform3uiv		
#define glUniform4uiv		
#define glTexParameterIiv		
#define glTexParameterIuiv		
#define glGetTexParameterIiv	
#define glGetTexParameterIuiv	
#define glClearBufferiv		
#define glClearBufferuiv		
#define glClearBufferfv		
#define glClearBufferfi		
#define glGetStringi	
#define glIsRenderbuffer	
#define glBindRenderbuffer		
#define glDeleteRenderbuffers	
#define glGenRenderbuffers		
#define glRenderbufferStorage	
#define glGetRenderbufferParameteriv
#define glIsFramebuffer	
#define glBindFramebuffer		
#define glDeleteFramebuffers	
#define glGenFramebuffers		
#define glCheckFramebufferStatus	
#define glFramebufferTexture1D	
#define glFramebufferTexture2D	
#define glFramebufferTexture3D	
#define glFramebufferRenderbuffer	
#define glGetFramebufferAttachmentParameteriv	
#define glGenerateMipmap		
#define glBlitFramebuffer		
#define glRenderbufferStorageMultisample
#define glFramebufferTextureLayer	
#define glMapBufferRange		
#define glFlushMappedBufferRange	
#define glBindVertexArray		
#define glDeleteVertexArrays	
#define glGenVertexArrays		
#define glIsVertexArray	
#define glDrawArraysInstanced	
#define glDrawElementsInstanced	
#define glTexBuffer		
#define glPrimitiveRestartIndex	
#define glCopyBufferSubData	
#define glGetUniformIndices	
#define glGetActiveUniformsiv	
#define glGetActiveUniformName	
#define glGetUniformBlockIndex		
#define glGetActiveUniformBlockiv	
#define glGetActiveUniformBlockName
#define glUniformBlockBinding	
#define glDrawElementsBaseVertex	
#define glDrawRangeElementsBaseVertex	
#define glDrawElementsInstancedBaseVertex	
#define glMultiDrawElementsBaseVertex	
#define glProvokingVertex		
#define glFenceSync		
#define glIsSync		
#define glDeleteSync		
#define glClientWaitSync		
#define glWaitSync		
#define glGetInteger64v		
#define glGetSynciv		
#define glGetInteger64i_v		
#define glGetBufferParameteri64v	
#define glFramebufferTexture	
#define glTexImage2DMultisample	
#define glTexImage3DMultisample	
#define glGetMultisamplefv		
#define glSampleMaski		
#define glBindFragDataLocationIndexed
#define glGetFragDataIndex
#define glGenSamplers		
#define glDeleteSamplers		
#define glIsSampler		
#define glBindSampler		
#define glSamplerParameteri	
#define glSamplerParameteriv	
#define glSamplerParameterf	
#define glSamplerParameterfv	
#define glSamplerParameterIiv	
#define glSamplerParameterIuiv	
#define glGetSamplerParameteriv	
#define glGetSamplerParameterIiv	
#define glGetSamplerParameterfv	
#define glGetSamplerParameterIuiv	
#define glQueryCounter		
#define glGetQueryObjecti64v	
#define glGetQueryObjectui64v	
#define glVertexAttribDivisor	
#define glVertexAttribP1ui		
#define glVertexAttribP1uiv	
#define glVertexAttribP2ui		
#define glVertexAttribP2uiv	
#define glVertexAttribP3ui		
#define glVertexAttribP3uiv	
#define glVertexAttribP4ui		
#define glVertexAttribP4uiv	
#define glVertexP2ui		
#define glVertexP2uiv		
#define glVertexP3ui		
#define glVertexP3uiv		
#define glVertexP4ui		
#define glVertexP4uiv		
#define glTexCoordP1ui		
#define glTexCoordP1uiv		
#define glTexCoordP2ui		
#define glTexCoordP2uiv		
#define glTexCoordP3ui		
#define glTexCoordP3uiv		
#define glTexCoordP4ui		
#define glTexCoordP4uiv		
#define glMultiTexCoordP1ui	
#define glMultiTexCoordP1uiv	
#define glMultiTexCoordP2ui	
#define glMultiTexCoordP2uiv	
#define glMultiTexCoordP3ui	
#define glMultiTexCoordP3uiv	
#define glMultiTexCoordP4ui	
#define glMultiTexCoordP4uiv	
#define glNormalP3ui		
#define glNormalP3uiv		
#define glColorP3ui		
#define glColorP3uiv		
#define glColorP4ui		
#define glColorP4uiv		
#define glSecondaryColorP3ui	
#define glSecondaryColorP3uiv	
#define glMinSampleShading		
#define glBlendEquationi		
#define glBlendEquationSeparatei	
#define glBlendFunci		
#define glBlendFuncSeparatei	
#define glDrawArraysIndirect	
#define glDrawElementsIndirect	
#define glUniform1d		
#define glUniform2d		
#define glUniform3d		
#define glUniform4d		
#define glUniform1dv		
#define glUniform2dv		
#define glUniform3dv		
#define glUniform4dv		
#define glUniformMatrix2dv		
#define glUniformMatrix3dv		
#define glUniformMatrix4dv		
#define glUniformMatrix2x3dv	
#define glUniformMatrix2x4dv	
#define glUniformMatrix3x2dv	
#define glUniformMatrix3x4dv	
#define glUniformMatrix4x2dv	
#define glUniformMatrix4x3dv	
#define glGetUniformdv		
#define glGetSubroutineUniformLocation	
#define glGetSubroutineIndex			
#define glGetActiveSubroutineUniformiv	
#define glGetActiveSubroutineUniformName	
#define glGetActiveSubroutineName		
#define glUniformSubroutinesuiv		
#define glGetUniformSubroutineuiv		
#define glGetProgramStageiv		
#define glPatchParameteri			
#define glPatchParameterfv			
#define glBindTransformFeedback		
#define glDeleteTransformFeedbacks		
#define glGenTransformFeedbacks		
#define glIsTransformFeedback		
#define glPauseTransformFeedback		
#define glResumeTransformFeedback		
#define glDrawTransformFeedback		
#define glDrawTransformFeedbackStream	
#define glBeginQueryIndexed		
#define glEndQueryIndexed			
#define glGetQueryIndexediv		
#define glReleaseShaderCompiler		
#define glShaderBinary			
#define glGetShaderPrecisionFormat		
#define glDepthRangef			
#define glClearDepthf			
#define glGetProgramBinary			
#define glProgramBinary			
#define glProgramParameteri		
#define glUseProgramStages			
#define glActiveShaderProgram		
#define glCreateShaderProgramv			
#define glBindProgramPipeline		
#define glDeleteProgramPipelines		
#define glGenProgramPipelines		
#define glIsProgramPipeline		
#define glGetProgramPipelineiv		
#define glProgramUniform1i			
#define glProgramUniform1iv		
#define glProgramUniform1f			
#define glProgramUniform1fv		
#define glProgramUniform1d			
#define glProgramUniform1dv		
#define glProgramUniform1ui		
#define glProgramUniform1uiv		
#define glProgramUniform2i			
#define glProgramUniform2iv		
#define glProgramUniform2f			
#define glProgramUniform2fv		
#define glProgramUniform2d			
#define glProgramUniform2dv		
#define glProgramUniform2ui		
#define glProgramUniform2uiv		
#define glProgramUniform3i			
#define glProgramUniform3iv		
#define glProgramUniform3f			
#define glProgramUniform3fv		
#define glProgramUniform3d			
#define glProgramUniform3dv		
#define glProgramUniform3ui		
#define glProgramUniform3uiv		
#define glProgramUniform4i			
#define glProgramUniform4iv		
#define glProgramUniform4f			
#define glProgramUniform4fv		
#define glProgramUniform4d			
#define glProgramUniform4dv		
#define glProgramUniform4ui		
#define glProgramUniform4uiv		
#define glProgramUniformMatrix2fv		
#define glProgramUniformMatrix3fv		
#define glProgramUniformMatrix4fv		
#define glProgramUniformMatrix2dv		
#define glProgramUniformMatrix3dv		
#define glProgramUniformMatrix4dv		
#define glProgramUniformMatrix2x3fv	
#define glProgramUniformMatrix3x2fv	
#define glProgramUniformMatrix2x4fv	
#define glProgramUniformMatrix4x2fv	
#define glProgramUniformMatrix3x4fv	
#define glProgramUniformMatrix4x3fv	
#define glProgramUniformMatrix2x3dv	
#define glProgramUniformMatrix3x2dv	
#define glProgramUniformMatrix2x4dv	
#define glProgramUniformMatrix4x2dv	
#define glProgramUniformMatrix3x4dv	
#define glProgramUniformMatrix4x3dv	
#define glValidateProgramPipeline		
#define glGetProgramPipelineInfoLog	
#define glVertexAttribL1d		
#define glVertexAttribL2d		
#define glVertexAttribL3d		
#define glVertexAttribL4d		
#define glVertexAttribL1dv		
#define glVertexAttribL2dv		
#define glVertexAttribL3dv		
#define glVertexAttribL4dv		
#define glVertexAttribLPointer	
#define glGetVertexAttribLdv	
#define glViewportArrayv		
#define glViewportIndexedf		
#define glViewportIndexedfv	
#define glScissorArrayv		
#define glScissorIndexed		
#define glScissorIndexedv		
#define glDepthRangeArrayv		
#define glDepthRangeIndexed	
#define glGetFloati_v		
#define glGetDoublei_v		
#define glDrawArraysInstancedBaseInstance	
#define glDrawElementsInstancedBaseInstance
#define glDrawElementsInstancedBaseVertexBaseInstance
#define glGetInternalformativ
#define glGetActiveAtomicCounterBufferiv
#define glBindImageTexture		
#define glMemoryBarrier	
#define glTexStorage1D	
#define glTexStorage2D	
#define glTexStorage3D	
#define glDrawTransformFeedbackInstanced
#define glDrawTransformFeedbackStreamInstanced
#define glClearBufferData		
#define glClearBufferSubData	
#define glDispatchCompute		
#define glDispatchComputeIndirect	
#define glCopyImageSubData		
#define glFramebufferParameteri	
#define glGetFramebufferParameteriv
#define glGetInternalformati64v	
#define glInvalidateTexSubImage	
#define glInvalidateTexImage	
#define glInvalidateBufferSubData	
#define glInvalidateBufferData	
#define glInvalidateFramebuffer	
#define glInvalidateSubFramebuffer	
#define glMultiDrawArraysIndirect	
#define glMultiDrawElementsIndirect
#define glGetProgramInterfaceiv	
#define glGetProgramResourceIndex	
#define glGetProgramResourceName	
#define glGetProgramResourceiv	
#define glGetProgramResourceLocation
#define glGetProgramResourceLocationIndex
#define glShaderStorageBlockBinding
#define glTexBufferRange
#define glTexStorage2DMultisample		
#define glTexStorage3DMultisample	
#define glTextureView		
#define glBindVertexBuffer		
#define glVertexAttribFormat	
#define glVertexAttribIFormat	
#define glVertexAttribLFormat	
#define glVertexAttribBinding	
#define glVertexBindingDivisor	
#define glDebugMessageControl	
#define glDebugMessageInsert	
#define glDebugMessageCallback	
#define glGetDebugMessageLog		
#define glPushDebugGroup		
#define glPopDebugGroup		
#define glObjectLabel		
#define glGetObjectLabel		
#define glObjectPtrLabel		
#define glGetObjectPtrLabel	
#define glGetPointerv		
#define glBufferStorage		
#define glClearTexImage		
#define glClearTexSubImage		
#define glBindBuffersBase		
#define glBindBuffersRange		
#define glBindTextures		
#define glBindSamplers		
#define glBindImageTextures	
#define glBindVertexBuffers	
#define glClipControl		
#define glCreateTransformFeedbacks	
#define glTransformFeedbackBufferBase	
#define glTransformFeedbackBufferRange	
#define glGetTransformFeedbackiv		
#define glGetTransformFeedbacki_v		
#define glGetTransformFeedbacki64_v	
#define glCreateBuffers		
#define glNamedBufferStorage		
#define glNamedBufferData		 
#define glNamedBufferSubData		
#define glCopyNamedBufferSubData		
#define glClearNamedBufferData		
#define glClearNamedBufferSubData		
#define glMapNamedBuffer		 
#define glMapNamedBufferRange		
#define glUnmapNamedBuffer		
#define glFlushMappedNamedBufferRange	
#define glGetNamedBufferParameteriv	
#define glGetNamedBufferParameteri64v	
#define glGetNamedBufferPointerv		
#define glGetNamedBufferSubData		
#define glCreateFramebuffers		
#define glNamedFramebufferRenderbuffer	
#define glNamedFramebufferParameteri	
#define glNamedFramebufferTexture		
#define glNamedFramebufferTextureLayer	
#define glNamedFramebufferDrawBuffer	
#define glNamedFramebufferDrawBuffers	
#define glNamedFramebufferReadBuffer	
#define glInvalidateNamedFramebufferData	
#define glInvalidateNamedFramebufferSubData
#define glClearNamedFramebufferiv		
#define glClearNamedFramebufferuiv		
#define glClearNamedFramebufferfv		
#define glClearNamedFramebufferfi		
#define glBlitNamedFramebuffer		
#define glCheckNamedFramebufferStatus		
#define glGetNamedFramebufferParameteriv
#define glGetNamedFramebufferAttachmentParameteriv
#define glCreateRenderbuffers	
#define glNamedRenderbufferStorage	
#define glNamedRenderbufferStorageMultisample
#define glGetNamedRenderbufferParameteriv
#define glCreateTextures		
#define glTextureBuffer		
#define glTextureBufferRange	
#define glTextureStorage1D		
#define glTextureStorage2D		
#define glTextureStorage3D		
#define glTextureStorage2DMultisample
#define glTextureStorage3DMultisample
#define glTextureSubImage1D	  
#define glTextureSubImage2D	  
#define glTextureSubImage3D	  
#define glCompressedTextureSubImage1D
#define glCompressedTextureSubImage2D
#define glCompressedTextureSubImage3D
#define glCopyTextureSubImage1D		
#define glCopyTextureSubImage2D		
#define glCopyTextureSubImage3D		
#define glTextureParameterf		
#define glTextureParameterfv		
#define glTextureParameteri		
#define glTextureParameterIiv		
#define glTextureParameterIuiv		
#define glTextureParameteriv		
#define glGenerateTextureMipmap		
#define glBindTextureUnit
#define glGetTextureImage
#define glGetCompressedTextureImage	
#define glGetTextureLevelParameterfv	
#define glGetTextureLevelParameteriv	
#define glGetTextureParameterfv		
#define glGetTextureParameterIiv		
#define glGetTextureParameterIuiv		
#define glGetTextureParameteriv		
#define glCreateVertexArrays		
#define glDisableVertexArrayAttrib		
#define glEnableVertexArrayAttrib		
#define glVertexArrayElementBuffer		
#define glVertexArrayVertexBuffer		
#define glVertexArrayVertexBuffers		
#define glVertexArrayAttribBinding		
#define glVertexArrayAttribFormat		
#define glVertexArrayAttribIFormat		
#define glVertexArrayAttribLFormat		
#define glVertexArrayBindingDivisor	
#define glGetVertexArrayiv
#define glGetVertexArrayIndexediv		
#define glGetVertexArrayIndexed64iv	
#define glCreateSamplers
#define glCreateProgramPipelines		
#define glCreateQueries
#define glGetQueryBufferObjecti64v		
#define glGetQueryBufferObjectiv		
#define glGetQueryBufferObjectui64v	
#define glGetQueryBufferObjectuiv		
#define glMemoryBarrierByRegion		
#define glGetTextureSubImage		
#define glGetCompressedTextureSubImage	
#define glGetGraphicsResetStatus		
#define glGetnCompressedTexImage		
#define glGetnTexImage	
#define glGetnUniformdv	
#define glGetnUniformfv	
#define glGetnUniformiv	
#define glGetnUniformuiv	
#define glReadnPixels	
#define glGetnMapdv	
#define glGetnMapfv	
#define glGetnMapiv	
#define glGetnPixelMapfv	
#define glGetnPixelMapuiv	
#define glGetnPixelMapusv	
#define glGetnPolygonStipple		
#define glGetnColorTable
#define glGetnConvolutionFilter		
#define glGetnSeparableFilter		
#define glGetnHistogram
#define glGetnMinmax
#define glTextureBarrier
#define glSpecializeShader
#define glMultiDrawArraysIndirectCount	
#define glMultiDrawElementsIndirectCount	
#define glPolygonOffsetClamp		
