#pragma once
#include <Godot.pkg.h>

#define module godot, API, Type, Variant

moduleValuesDef(FuncNames,
	.NewCopy			= "variant_new_copy",
	.NewNil				= "variant_new_nil",
	.Destroy			= "variant_destroy",
	.Call				= "variant_call",
	.CallStatic			= "variant_call_static",
	.Evaluate			= "variant_evaluate",
	.Set				= "variant_set",
	.SetNamed			= "variant_set_named",
	.SetKeyed			= "variant_set_keyed",
	.SetIndexed			= "variant_set_indexed",
	.Get				= "variant_get",
	.GetNamed			= "variant_get_named",
	.GetKeyed			= "variant_get_keyed",
	.GetIndexed			= "variant_get_indexed",
	.IterInit			= "variant_iter_init",
	.IterNext			= "variant_iter_next",
	.IterGet			= "variant_iter_get",
	.Hash				= "variant_hash",
	.RecursiveHash			= "variant_recursive_hash",
	.HashCompare			= "variant_hash_compare",
	.Booleanize			= "variant_booleanize",
	.Duplicate			= "variant_duplicate",
	.Stringify			= "variant_stringify",
	.GetType			= "variant_get_type",
	.HasMethod			= "variant_has_method",
	.HasMember			= "variant_has_member",
	.HasKey				= "variant_has_key",
	.GetObjectInstanceId		= "variant_get_object_instance_id",
	.GetTypeName			= "variant_get_type_name",
	.CanConvert			= "variant_can_convert",
	.CanConvertStrict		= "variant_can_convert_strict",
	.GetVariantFromTypeConstructor	= "get_variant_from_type_constructor",
	.GetVariantToTypeConstructor	= "get_variant_to_type_constructor",
	.GetVariantGetInternalPtrFunc	= "variant_get_ptr_internal_getter",
	.Construct			= "variant_construct",
	.GetPtrOperatorEvaluator	= "variant_get_ptr_operator_evaluator",
	.GetPtrBuiltinMethod		= "variant_get_ptr_builtin_method",
	.GetPtrConstructor		= "variant_get_ptr_constructor",
	.GetPtrDestructor		= "variant_get_ptr_destructor",
	.GetPtrSetter			= "variant_get_ptr_setter",
	.GetPtrGetter			= "variant_get_ptr_getter",
	.GetPtrIndexedSetter		= "variant_get_ptr_indexed_setter",
	.GetPtrIndexedGetter		= "variant_get_ptr_indexed_getter",
	.GetPtrKeyedSetter		= "variant_get_ptr_keyed_setter",
	.GetPtrKeyedGetter		= "variant_get_ptr_keyed_getter",
	.GetPtrKeyedChecker		= "variant_get_ptr_keyed_checker",
	.GetConstantValue		= "variant_get_constant_value",
	.GetPtrUtilityFunction          = "variant_get_ptr_utility_function"
)

moduleValues(TypeID,
	NIL,, 			
	INT,,			
	FLOAT,,
	STRING,,			
	VECTOR2,, 		
	VECTOR2I,,		
	RECT2,,			
	RECT2I,,			
	VECTOR3,,		
	VECTOR3I,,		
	TRANSFORM2D,,		
	VECTOR4,,		
	VECTOR4I,,		
	PLANE,,			
	QUATERNION,,		
	AABB,,			
	BASIS,,			
	TRANSFORM3D,,		
	PROJECTION,,		
	COLOR,,			
	STRING_NAME,,		
	NODE_PATH,,		
	RID,,			
	OBJECT,,			
	CALLABLE,,		
	SIGNAL,,			
	DICTIONARY,,		
	ARRAY,,			
	PACKED_BYTE_ARRAY,,	
	PACKED_INT32_ARRAY,,	
	PACKED_INT64_ARRAY,,	
	PACKED_FLOAT32_ARRAY,,	
	PACKED_FLOAT64_ARRAY,,	
	PACKED_STRING_ARRAY,,	
	PACKED_VECTOR2_ARRAY,,	
	PACKED_VECTOR3_ARRAY,,	
	PACKED_COLOR_ARRAY,,	
	PACKED_VECTOR4_ARRAY,,
)

moduleValues(OpID,
	EQUAL,,		
	NOT_EQUAL,,	
	LESS,,		
	LESS_EQUAL,,	
	GREATER,,	
	GREATER_EQUAL,,	
			
	ADD,,		
	SUBTRACT,,	
	MULTIPLY,,	
	DIVIDE,,		
	NEGATE,,		
	POSITIVE,,	
	MODULE,,		
	POWER,,		
			
	SHIFT_LEFT,,	
	SHIFT_RIGHT,,	
	BIT_AND,,	
	BIT_OR,,		
	BIT_XOR,,	
	BIT_NEGATE,,	
			
	AND,,		
	OR,,		
	XOR,,		
	NOT,,		
			
	IN,,		
	MAX,,		
)

export(
SUBMODULE(), 
VALUES(FuncNames, OpID, TypeID), 
	load
)

#undef module
